apiVersion: v1
kind: Service
metadata:
  name: sbc-inbound
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: sbc-inbound
spec:
  selector:
    app: sbc-inbound
  ports:
    - name: sbc-inbound
      port: {{ .Values.sbcInbound.ports.tcp }}
      targetPort: {{ .Values.sbcInbound.ports.tcp }}
      protocol: TCP
