{{- if .Values.vgConnector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vg-connector
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: vg-connector
spec:
  selector:
    app: vg-connector
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.vgConnector.port }}
      targetPort: {{ .Values.vgConnector.port }}
{{- end }}
