apiVersion: v1
kind: ConfigMap
metadata:
  name: cognigy-env
  namespace: {{ $.Release.Namespace | quote }}
data:  
{{- range $key, $value := .Values.cognigyEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}