apiVersion: v2
name: voicegateway
description: A Helm Chart for Cognigy VoiceGateway
version: "4.51.1"
appVersion: "0.8.3-rc2"
kubeVersion: ">=v1.19.0-0,<v1.25.0-0"
home: https://cognigy.com
icon: https://www.cognigy.com/hubfs/Cognigy.svg
maintainers:
  - name: VoiceGateway Team
    email: voicegateway@cognigy.com
sources:
  - https://github.com/Cognigy/cognigy-ai-helm-chart
  - https://github.com/Cognigy/cognigy-vg-helm-chart
dependencies:
  - name: traefik
    version: "10.19.4"
    repository: "https://helm.traefik.io/traefik"
    condition: traefik.enabled
  - name: postgresql
    version: "11.9.13"
    # Because of the issue https://github.com/bitnami/charts/issues/10539 we can't use the regular url "https://charts.bitnami.com/bitnami/postgresql"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: postgresql.enabled
  - name: mysql
    version: "9.9.1"
    # Because of the issue https://github.com/bitnami/charts/issues/10539 we can't use the regular url "https://charts.bitnami.com/bitnami/mysql"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: mysql.enabled
