apiVersion: v2
name: voicegateway
description: A Helm Chart for Cognigy VoiceGateway
version: "4.90.0"
appVersion: "0.9.2"
kubeVersion: ">=v1.23.0-0,<v1.31.0-0"
home: https://cognigy.com
icon: https://www.cognigy.com/hubfs/Cognigy.svg
maintainers:
  - name: VoiceGateway Team
    email: voicegateway@cognigy.com
sources:
  - https://github.com/Cognigy/cognigy-ai-helm-chart
  - https://github.com/Cognigy/cognigy-vg-helm-chart
dependencies:
  - name: traefik
    version: "32.1.1"
    repository: "https://helm.traefik.io/traefik"
    condition: traefik.enabled
  - name: postgresql
    version: "11.9.13"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: postgresql.enabled
  - name: mysql
    version: "9.18.0"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: mysql.enabled
  - name: redis
    version: "17.4.1"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: redisHa.enabled
    alias: redisHa
