apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: influxdb
spec:
  serviceName: influxdb
  replicas: {{ .Values.influxdb.replicaCount }}
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
      annotations:
        checksum/cognigy-env: {{ include (print $.Template.BasePath "/configurations/cognigy-env.yaml") $ | sha256sum }}
    spec:
      restartPolicy: Always
      containers:
        - name: influxdb
          image: {{ .Values.influxdb.image }}
          imagePullPolicy: {{ .Values.influxdb.imagePullPolicy }}
          resources: {}
          ports:
            - name: influxdb
              containerPort: {{ .Values.influxdb.port }}
              protocol: TCP
          env:
            - name: INFLUXDB_LOGGING_LEVEL
              value: {{ .Values.influxdb.logLevel }}
          envFrom:
            - configMapRef:
                name: cognigy-env
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.influxdb.port }}
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.influxdb.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
          volumeMounts:
          - name: influxdb
            mountPath: /var/lib/influxdb
  volumeClaimTemplates:
  - metadata:
      name: influxdb
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.influxdb.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.influxdb.storage }}
