apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: influxdb
spec:
  serviceName: influxdb
  replicas: {{ .Values.influxdb.replicaCount }}
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb
    spec:
      {{- include "image.pullSecrets" $ | nindent 6 }}
      {{- if .Values.influxdb.affinity }}
      affinity: {{- include "cognigyvg.common.tplvalues.render" (dict "value" .Values.influxdb.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.influxdb.nodeSelector }}
      nodeSelector: {{- include "cognigyvg.common.tplvalues.render" (dict "value" .Values.influxdb.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.influxdb.priorityClassName }}
      priorityClassName: {{ .Values.influxdb.priorityClassName }}
      {{- end }}
      {{- if .Values.influxdb.podSecurityContext }}
      securityContext: {{- include "cognigyvg.common.tplvalues.render" (dict "value" .Values.influxdb.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.influxdb.tolerations }}
      tolerations: {{- include "cognigyvg.common.tplvalues.render" (dict "value" .Values.influxdb.tolerations "context" $) | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
        - name: influxdb
          image: {{ .Values.influxdb.image }}
          imagePullPolicy: {{ .Values.influxdb.imagePullPolicy }}
          resources: {{- toYaml .Values.influxdb.resources | nindent 12 }}
          ports:
            - name: influxdb
              containerPort: {{ .Values.influxdb.port }}
              protocol: TCP
          env:
            - name: INFLUXDB_LOGGING_LEVEL
              value: {{ .Values.influxdb.logLevel }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.influxdb.port }}
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.influxdb.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
          volumeMounts:
          - name: influxdb
            mountPath: /var/lib/influxdb
  volumeClaimTemplates:
  - metadata:
      name: influxdb
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.influxdb.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.influxdb.storage }}
