apiVersion: batch/v1
kind: Job
metadata:
  name: api-migrator-{{ .Release.Revision }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    owner-team: echo
  annotations:
    {{- if .Values.apiMigrator.hookEnabled }}
    # This is what defines this resource as a hook. Without these lines, the
    # resource is considered part of the release.
    "helm.sh/hook": {{ .Values.apiMigrator.hook | quote }}
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": {{ .Values.apiMigrator.hookDeletePolicy | quote }}
    {{- end }}
spec:
  backoffLimit: 10
  ttlSecondsAfterFinished: 86400 # 1 day
  template:
    metadata:
      name: api-migrator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
    {{- include "image.pullSecrets" $ | nindent 6 }}
      restartPolicy: OnFailure
      containers:
        - name: api-migrator-init
          image: {{ include "vg.common.image.render" (dict "global" $.Values.global "image" .Values.apiMigrator.image) }}
          imagePullPolicy: {{ .Values.apiMigrator.imagePullPolicy }}
          env:
            - name: JAMBONES_MYSQL_HOST
              value: {{ .Values.mysql.host }}
            - name: JAMBONES_MYSQL_DATABASE
              value: {{ .Values.mysql.database.name | quote }}
            - name: JAMBONES_MYSQL_USER
              value: {{ .Values.mysql.auth.username | quote }}
            - name: JAMBONES_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voicegateway-mysql-password
                  key: mysql-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: voicegateway-jwt
                  key: jwt
            - name: JAMBONES_TIME_SERIES_HOST
              value: {{ .Values.influxdb.host }}
            - name: API_MIGRATION_TARGET
              value: {{ .Values.apiMigrator.migrationTarget }}
            {{- if .Values.apiMigrator.extraEnvVars }}
            {{- include "vg.common.tplvalues.render" (dict "value" .Values.apiMigrator.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.apiMigrator.logCollectorEnabled }}
        - name: log-collector
          image: fluentd
          imagePullPolicy: {{ .Values.apiMigrator.imagePullPolicy }}
        {{- end }}