{{- if and (.Values.postgresql.enabled) (eq .Values.cloud "aws") -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.aws.postgresql.storageClassName | quote }}
provisioner: {{ .Values.aws.postgresql.provisionerName | default "kubernetes.io/aws-ebs" | quote }}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: {{ .Values.aws.postgresql.awsEBSVolumeType | default "gp2" | quote }}
  fsType: ext4
  encrypted: "true"
{{- end -}}
