{{- if .Values.apiBan.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-api-ban-list
spec:
  schedule: {{ .Values.apiBan.cronjobSchedule }}
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: {{ .Values.apiBan.cronjobTtlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            app: update-api-ban-list
          annotations:
            checksum/cognigy-env: {{ include (print $.Template.BasePath "/configurations/cognigy-env.yaml") $ | sha256sum }}
        spec:
          containers:
            - name: api-ban
              image: {{ .Values.apiBan.image }}
              imagePullPolicy: {{ .Values.apiBan.imagePullPolicy }}
              env:
                - name: API_BAN_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: voicegateway-api-ban-key-secret
                      key: apiKey
                - name: API_BAN_URL
                  value: {{ .Values.apiBan.endpoint }}
                - name: API_BAN_BANNED_RANGES
                  value: {{ .Values.apiBan.bannedIpsList }}
                - name: REDIS_HOST
                  value: {{ .Values.redis.host }}
                - name: REDIS_PORT
                  value: {{ .Values.redis.port | quote }}
                {{- if .Values.apiBan.extraEnvVars }}
                {{- include "vg.common.tplvalues.render" (dict "value" .Values.apiBan.extraEnvVars "context" $) | nindent 12 }}
                {{- end }}
              envFrom:
                - configMapRef:
                    name: cognigy-env
          restartPolicy: Never
          imagePullSecrets:
            - name: cognigy-registry-token
{{- end }}