{{- if and (.Values.apiBan.enabled) (not .Values.apiBan.apiKey.existingKey) (not (lookup "v1" "Secret" $.Release.Namespace "voicegateway-api-ban-key-secret")) }}
apiVersion: v1
kind: Secret
metadata:
  name: voicegateway-api-ban-key-secret
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  apiKey: {{ .Values.apiBan.apiKey.key | b64enc | quote }}
{{- end }}