apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telegraf
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: telegraf
spec:
  serviceName: telegraf
  replicas: {{ .Values.telegraf.replicaCount }}
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      name: telegraf
      labels:
        app: telegraf
      annotations:
        checksum/telegraf: {{ include (print $.Template.BasePath "/telegraf/config-map.yaml") $ | sha256sum }}
    spec:
      {{- include "image.pullSecrets" $ | nindent 6 }}
      {{- if .Values.telegraf.affinity }}
      affinity: {{- include "vg.common.tplvalues.render" (dict "value" .Values.telegraf.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.telegraf.nodeSelector }}
      nodeSelector: {{- include "vg.common.tplvalues.render" (dict "value" .Values.telegraf.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.telegraf.priorityClassName }}
      priorityClassName: {{ .Values.telegraf.priorityClassName }}
      {{- end }}
      {{- if .Values.telegraf.podSecurityContext }}
      securityContext: {{- include "vg.common.tplvalues.render" (dict "value" .Values.telegraf.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.telegraf.tolerations }}
      tolerations: {{- include "vg.common.tplvalues.render" (dict "value" .Values.telegraf.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: telegraf
          image: {{ .Values.telegraf.image }}
          imagePullPolicy: {{ .Values.telegraf.imagePullPolicy }}
          resources: {{- toYaml .Values.telegraf.resources | nindent 12 }}
          ports:
            - name: telegraf
              containerPort: {{ .Values.telegraf.port }}
              protocol: TCP
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
      restartPolicy: Always
      volumes:
      - name: telegraf-config
        configMap:
          name: telegraf
          items:
          - key: telegraf.conf
            path: telegraf.conf