apiVersion: v1
kind: Service
metadata:
  name: sbc-rtp
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: sbc-rtp
spec:
  selector:
    app: sbc-rtp
  ports:
    - name: sbc-rtp
      port: {{ .Values.sbc.rtp.port }}
      targetPort: {{ .Values.sbc.rtp.port }}
      protocol: UDP
