{{- if eq .Values.cloud "gcp" -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.gcp.influxdb.storageClassName | quote }}
provisioner: {{ .Values.gcp.influxdb.provisionerName | quote }}
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: {{ .Values.gcp.influxdb.pdType | default "pd-balanced" | quote }}
{{- end -}}