{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-server
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- if .Values.tls.enabled }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    {{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
    {{- end }}
    {{- if .Values.ingress.api.ipWhiteListMiddleware.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-ipwhitelistapiserver@kubernetescrd
    {{- end }}
spec:
  ingressClassName: traefik
  {{- include "tlsCertificate.secretName.render" $ | nindent 2 }}
  rules:
    - host: {{ .Values.ingress.api.host }}
      http:
        paths:
          - backend:
              service:
                name: api-server
                port:
                  number: {{ .Values.api.port }}
            path: /
            pathType: Prefix
{{- end }}