apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: api-server
    owner-team: echo
spec:
  selector:
    app: api-server
  ports:
    - name: api-server
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
