{{ if and .Values.api.vgTeam.enabled (not (lookup "v1" "Secret" $.Release.Namespace "vg-team-default-password")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vg-team-default-password
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    owner-team: echo
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # randomly generated 20 character password
  defaultUserPassword: "{{ randAlphaNum 20 | b64enc }}"
{{- end }}

