{{- if .Values.homer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: homer
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: homer
    owner-team: echo
spec:
  selector:
    app: homer
  type: NodePort
  ports:
    - name: homer
      port: {{ .Values.homer.port }}
      targetPort: {{ .Values.homer.port }}
      protocol: TCP
{{- end }}