apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: grafana
spec:
  serviceName: grafana
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
      annotations:
        checksum/cognigy-env: {{ include (print $.Template.BasePath "/configurations/cognigy-env.yaml") $ | sha256sum }}
    spec:
      securityContext:
          runAsUser: 472
          fsGroup: 472
      restartPolicy: Always
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}
          imagePullPolicy: {{ .Values.heplifyServer.imagePullPolicy }}
          resources: {}          
          ports:
            - name: grafana
              containerPort: {{ .Values.grafana.port }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.grafana.port }}
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              port: {{ .Values.grafana.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          volumeMounts:
            - name: grafana-claim
              mountPath: /var/lib/grafana
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/dashboards/default.yaml
              subPath: default-dashboard.yaml
            - name: grafana-config
              mountPath: /var/lib/grafana/dashboards/voicegateway-dashboard.json
              subPath: voicegateway-dashboard.json
            - name: grafana-config
              mountPath: /var/lib/grafana/dashboards/voicegateway-heplify.json
              subPath: voicegateway-heplify.json
          envFrom:
            - configMapRef:
                name: cognigy-env
      volumes:
      - name: grafana-config
        configMap:
          name: grafana
          items:
          - key: datasource.yaml
            path: datasource.yaml
          - key: default-dashboard.yaml
            path: default-dashboard.yaml
          - key: voicegateway-dashboard.json
            path: voicegateway-dashboard.json
          - key: voicegateway-heplify.json
            path: voicegateway-heplify.json
  volumeClaimTemplates:
  - metadata:
      name: grafana-claim
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.grafana.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.grafana.storage }}
          
