apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - name: grafana
      port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}
      protocol: TCP
