{{- if (.Values.podMonitors.enabled) }}
{{- with .Values.podMonitors }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prom-cognigy-monitor-cognigy-vg-sbc-sip
  namespace: {{ .namespace }}
  labels:
    owner-team: echo
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
    - path: /metrics
      port: sip-drachtio
  selector:
    matchLabels:
      app: sbc-sip
{{- end }}
{{- end }}