apiVersion: v1
kind: Service
metadata:
  {{- if .Values.sbc.sip.useStatefulSet }}
  name: {{ .Values.sbc.sip.headlessServiceName | quote }}
  {{- else }}
  name: {{ .Values.sbc.sip.serviceName | quote }}
  {{- end }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: sbc-sip
spec:
  selector:
    app: sbc-sip
  {{- if .Values.sbc.sip.useStatefulSet }}
  clusterIP: None
  {{- end }}
  ports:
    - name: sip-tcp
      port: {{ .Values.sbc.sip.ports.tcp }}
      targetPort: {{ .Values.sbc.sip.ports.tcp }}
      protocol: TCP
    - name: sip-tls
      port: {{ .Values.sbc.sip.ports.tls }}
      targetPort: {{ .Values.sbc.sip.ports.tls }}
    - name: sip-udp
      port: {{ .Values.sbc.sip.ports.udp }}
      targetPort: {{ .Values.sbc.sip.ports.udp }}
      protocol: UDP
    - name: sip-wss
      port: {{ .Values.sbc.sip.ports.wss }}
      targetPort: {{ .Values.sbc.sip.ports.wss }}
