apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-call-history-billing-app
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-call-history
              image: alpine:3.17.0
              imagePullPolicy: IfNotPresent
              env:
                - name: URL
                  {{- if and (.Values.billingApp.updateCallHistoryEndpointProtocol) (.Values.ingress.billingApp.host) (.Values.billingApp.updateCallHistoryEndpointPath) }}
                  value: {{ printf "%s://%s%s" .Values.billingApp.updateCallHistoryEndpointProtocol .Values.ingress.billingApp.host .Values.billingApp.updateCallHistoryEndpointPath | quote }}
                  {{- else }}
                  value: {{ .Values.billingApp.updateCallHistoryEndpoint }}
                  {{- end }}

                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: billing-app-api-secret
                      key: secret
              args:
                - /bin/sh
                - -c
                - "apk --update add curl coreutils \
                && curl -X POST $URL -H 'x-api-key: '$API_KEY'' -H 'Content-Type: application/json' -d '{\"timestamp\": '$(date -d '-1 hour' +%s)'}'"
          restartPolicy: Never
