apiVersion: batch/v1
kind: CronJob
metadata:
  name: deactivate-account-billing
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: deactivate-account-billing
              image: alpine:3.17.0
              imagePullPolicy: IfNotPresent
              env:
                - name: URL
                  {{- if and (.Values.billingApp.endpointProtocol) (.Values.ingress.billingApp.host) (.Values.billingApp.deactivateAccountEndpointPath) }}
                  value: {{ printf "%s://%s%s" .Values.billingApp.endpointProtocol .Values.ingress.billingApp.host .Values.billingApp.deactivateAccountEndpointPath | quote }}
                  {{- else }}
                  value: {{ .Values.billingApp.endpoint }}
                  {{- end }}

                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: billing-app-api-secret
                      key: secret
              args:
                - /bin/sh
                - -c
                - "apk --update add curl coreutils \
                && curl -X POST $URL -H 'x-api-key: '$API_KEY'' -H 'Content-Type: application/json' -d '{\"timestamp\": '$(date +%s)'}'"
          restartPolicy: Never
