{{- if .Values.billingApp.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deactivate-account-billing
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: {{ .Values.billingApp.deactivateTtlSecondsAfterFinished }}
      template:
        spec:
          {{- include "image.pullSecrets" $ | nindent 10 }}
          containers:
            - name: deactivate-account-billing
              image: {{ include "vg.common.image.render" (dict "global" $.Values.global "image" .Values.jobs.image) }}
              imagePullPolicy: IfNotPresent
              env:
                - name: URL
                  {{- if and (.Values.billingApp.endpointProtocol) (.Values.ingress.billingApp.host) (.Values.billingApp.deactivateAccountEndpointPath) }}
                  value: {{ printf "%s://%s%s" .Values.billingApp.endpointProtocol .Values.ingress.billingApp.host .Values.billingApp.deactivateAccountEndpointPath | quote }}
                  {{- else }}
                  value: {{ .Values.billingApp.endpoint }}
                  {{- end }}

                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: billing-app-api-secret
                      key: secret
                {{- if .Values.billingApp.extraEnvVars }}
                {{- include "vg.common.tplvalues.render" (dict "value" .Values.billingApp.extraEnvVars "context" $) | nindent 12 }}
                {{- end }}
              args:
                - /bin/sh
                - -c
                - "curl -X POST $URL -H 'x-api-key: '$API_KEY'' -H 'Content-Type: application/json' -d '{\"timestamp\": '$(date +%s)'}'"
          restartPolicy: Never
{{- end }}
