{{- if .Values.billingApp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-app
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: billing-app
spec:
  replicas: {{ .Values.billingApp.replicasCount }}
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
      annotations:
        checksum/cognigy-env: {{ include (print $.Template.BasePath "/configurations/cognigy-env.yaml") $ | sha256sum }}
    spec:
      {{- include "image.pullSecrets" $ | nindent 6 }}
      {{- if .Values.billingApp.affinity }}
      affinity: {{- include "vg.common.tplvalues.render" (dict "value" .Values.billingApp.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.billingApp.nodeSelector }}
      nodeSelector: {{- include "vg.common.tplvalues.render" (dict "value" .Values.billingApp.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.billingApp.priorityClassName }}
      priorityClassName: {{ .Values.billingApp.priorityClassName }}
      {{- end }}
      {{- if .Values.billingApp.podSecurityContext }}
      securityContext: {{- include "vg.common.tplvalues.render" (dict "value" .Values.billingApp.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.billingApp.tolerations }}
      tolerations: {{- include "vg.common.tplvalues.render" (dict "value" .Values.billingApp.tolerations "context" $) | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
        - name: billing-app
          image: {{ .Values.billingApp.image }}
          imagePullPolicy: {{ .Values.billingApp.imagePullPolicy }}
          resources: {{- toYaml .Values.billingApp.resources | nindent 12 }}
          ports:
            - name: billing-app
              containerPort: {{ .Values.billingApp.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.health.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: {{ .Values.health.port }}
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 10 
          startupProbe:
            httpGet:
              path: /health/startup
              port: {{ .Values.health.port }}
          env:
            - name: NODE_ENV
              value: {{ .Values.global.nodeEnv | quote }}
            - name: PORT
              value: {{ .Values.billingApp.port | quote }}
            - name: VOICE_BILLING_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: billing-app-api-secret
                  key: secret
            - name: INFLUXDB_HOST
              value: {{ .Values.influxdb.host | quote }}
            - name: INFLUXDB_PORT
              value: {{ .Values.influxdb.port | quote }}
            - name: MYSQL_HOST
              value: {{ .Values.mysql.host | quote }}
            - name: MYSQL_PORT
              value: {{ .Values.mysql.port | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database.name | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.auth.username | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voicegateway-mysql-password
                  key: mysql-password
            - name: TRACING_ENABLED
              value: {{ .Values.tracing.enabled | quote }}
            - name: TRACING_BASE_URL_WITH_PROTOCOL
              value: {{ .Values.tracing.baseUrl | quote }}      
            - name: TRACING_ERRORS_ENABLED
              value: {{ .Values.tracing.errorsEnabled | quote }}
            - name: TRACING_SAMPLE_RATE
              value: {{ .Values.tracing.sampleRate | quote }}
            - name: TRACING_EVENTS_SAMPLE_RATE
              value: {{ .Values.tracing.eventsSampleRate | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.tracing.environment | quote }}
            - name: COGNIGY_AI_VERSION
              value: {{ .Chart.Version | trunc 6 | quote }}
            - name: VG_ENDPOINT
              value: {{ .Values.api.protocol }}://{{ .Values.ingress.api.host }}/v1
            - name: VG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{- include "billingAppUserCreds" $ | indent 1 }}
                  key: password
            - name: VG_USER
              valueFrom:
                secretKeyRef:
                  name: {{- include "billingAppUserCreds" $ | indent 1 }}
                  key: user
            {{- if .Values.billingApp.extraEnvVars }}
            {{- include "vg.common.tplvalues.render" (dict "value" .Values.billingApp.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: cognigy-env
{{- end }}