{{ if and (.Values.billingApp.enabled) (not (lookup "v1" "Secret" $.Release.Namespace "billing-app-api-secret")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-app-api-secret
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # use 128 bytes of random value, hex
  secret: "{{ printf "%x" (randAlphaNum 128) | b64enc }}"
{{- end }}
