{{- if .Values.billingApp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: billing-app
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: billing-app
spec:
  selector:
    app: billing-app
  ports:
    - name: billing-app
      port: {{ .Values.billingApp.port }}
      targetPort: {{ .Values.billingApp.port }}
      protocol: TCP
{{- end }}