{{- if .Values.testCallManager.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clean-up-test-call-manager
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: clean-up
            image: {{ .Values.jobs.image }}
            imagePullPolicy: IfNotPresent
            env:
              - name: URL
                {{- if and (.Values.testCallManager.cleanUpEndpointProtocol) (.Values.ingress.testCallManager.host) (.Values.testCallManager.cleanUpEndpointPath) }}
                value: {{ printf "%s://%s%s" .Values.testCallManager.cleanUpEndpointProtocol .Values.ingress.testCallManager.host .Values.testCallManager.cleanUpEndpointPath | quote }}
                {{- else }}
                value: {{ .Values.testCallManager.cleanUpEndpoint }}
                {{- end }}
              - name: API_KEY
                valueFrom:
                  secretKeyRef:
                    name: test-call-manager-api-secret
                    key: secret 
            args:
              - /bin/sh
              - -c
              - "curl -X DELETE $URL -H 'x-api-key: '$API_KEY'' -H 'Content-Type: application/json' -d '{\"timestamp\": '$(date +%s000)'}'"
          restartPolicy: Never
          imagePullSecrets:
            - name: cognigy-registry-token
{{- end }}