{{ if and (.Values.testCallManager.enabled) (not (lookup "v1" "Secret" $.Release.Namespace "test-call-manager-api-secret")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: test-call-manager-api-secret
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    owner-team: echo
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # use 128 bytes of random value, hex
  secret: "{{ printf "%x" (randAlphaNum 128) | b64enc }}"
{{- end }}
