{{- if and .Values.billing.enabled .Values.billing.sendToCentral.enabled }}
{{- if not (lookup "v1" "Secret" $.Release.Namespace (.Values.billing.sendToCentral.secretName | default "vg-billing-secret")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.billing.sendToCentral.secretName | default "vg-billing-secret" }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
    {{- if .Values.apiMigrator.hookEnabled }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-2"
    {{- end }}
type: Opaque
data:
  shared-secret: "{{ randAlphaNum 32 | b64enc }}"
{{- end }}
{{- end }}
