{{- if and (.Values.homer.enabled) (not (lookup "v1" "Secret" $.Release.Namespace "vg-homer-password")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vg-homer-password
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-2"
    
type: Opaque
data:
  # use 32 bytes of random value, hex
  homer-password: "{{ printf "%x" (randAlphaNum 32) | b64enc }}"
{{- end }}
