{{- if and (.Values.sbc.sipDnsUpdaterAzure.enabled) (not .Values.sbc.sipDnsUpdaterAzure.servicePrincipal.existingSecret ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sip-dns-updater-azure
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  ## Azure Tenant ID
  tenantId: {{ .Values.sbc.sipDnsUpdaterAzure.servicePrincipal.tenantId | b64enc | quote }}
  ## Application ID of the Service Principal
  appId: {{ .Values.sbc.sipDnsUpdaterAzure.servicePrincipal.appId | b64enc | quote }}
  ## Client secret of the Service Principal
  appPassword: {{ .Values.sbc.sipDnsUpdaterAzure.servicePrincipal.appPassword | b64enc | quote }}
{{- end }}