{{ if not (lookup "v1" "Secret" $.Release.Namespace "voicegateway-jwt") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: voicegateway-jwt
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
    {{- if .Values.dbCreate.hookEnabled }}
    # This is what defines this resource as a hook. Without these lines, the
    # resource is considered part of the release.
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
    {{- end }}
type: Opaque
data:
  # use 128 bytes of random value, hex
  jwt: "{{ printf "%x" (randAlphaNum 128) | b64enc }}"
{{- end }}