{{- if not (lookup "v1" "Secret" $.Release.Namespace "voicegateway-drachtio-secret") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: voicegateway-drachtio-secret
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
    {{- if .Values.apiMigrator.hookEnabled }}
    # This is what defines this resource as a hook. Without these lines, the
    # resource is considered part of the release.
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-2"
    {{- end }}
type: Opaque
data:
  # use 64 bytes of random value, hex
  secret: "{{ printf "%x" (randAlphaNum 64) | b64enc }}"
{{- end }}
