{{- if not (lookup "v1" "Secret" $.Release.Namespace "voicegateway-call-recording-credentials") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: voicegateway-call-recording-credentials
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
    {{- if .Values.dbCreate.hookEnabled }}
    # This is what defines this resource as a hook. Without these lines, the
    # resource is considered part of the release.
    "helm.sh/hook": {{ .Values.dbCreate.hook | quote }}
    "helm.sh/hook-weight": "-2"
    {{- end }}
type: Opaque
data:
  username: "{{ "voicegateway" | b64enc }}"
  # use 32 bytes of random value, hex
  password: "{{ printf "%x" (randAlphaNum 32) | b64enc }}"
{{- end }}