{{- if and .Values.vgTestHarness.enabled .Values.vgTestHarness.regionDns.enabled }}
{{- range list "eu" "intl" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-deepgram-{{ . }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "cognigy.com/source-code": "git@github.com:Cognigy/vg-test-harness.git"
  labels:
    app: mock-deepgram-{{ . }}
    owner-team: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-deepgram-{{ . }}
  template:
    metadata:
      labels:
        app: mock-deepgram-{{ . }}
    spec:
      {{- include "image.pullSecrets" $ | nindent 6 }}
      containers:
        - name: mock-deepgram-region
          image: {{ $.Values.vgTestHarness.mockDeepgramRegion.image }}
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_BIND_SERVICE"]
          args:
            - --listen-addr=:443
            - --region={{ . }}
          ports:
            - name: tls
              containerPort: 443
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{- toYaml $.Values.vgTestHarness.mockDeepgramRegion.resources | nindent 12 }}
---
{{- end }}
{{- end }}
