{{/* templates/test-harness/region-dns-deployment.yaml */}}
{{- if and .Values.vgTestHarness.enabled .Values.vgTestHarness.regionDns.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dns
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "cognigy.com/source-code": "git@github.com:Cognigy/vg-helm-chart.git"
  labels:
    app: test-dns
    owner-team: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dns
  template:
    metadata:
      labels:
        app: test-dns
      annotations:
        checksum/corefile: {{ include (print $.Template.BasePath "/test-harness/region-dns-configmap.yaml") . | sha256sum }}
    spec:
      {{- include "image.pullSecrets" $ | nindent 6 }}
      containers:
        - name: coredns
          image: {{ .Values.vgTestHarness.regionDns.image }}
          args: ["-conf", "/etc/coredns/Corefile"]
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/coredns
          resources: {{- toYaml .Values.vgTestHarness.regionDns.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: test-dns-corefile
{{- end }}
