{{/* templates/test-harness/region-dns-configmap.yaml */}}
{{- if and .Values.vgTestHarness.enabled .Values.vgTestHarness.regionDns.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-dns-corefile
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: test-dns
    owner-team: echo
data:
  Corefile: |
    . {
        rewrite name exact api.deepgram.com.    mock-deepgram-intl.{{ .Release.Namespace }}.svc.cluster.local.
        rewrite name exact api.eu.deepgram.com. mock-deepgram-eu.{{ .Release.Namespace }}.svc.cluster.local.
        forward . {{ .Values.vgTestHarness.regionDns.upstream }}
        log
        errors
    }
{{- end }}
