apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace | quote }}
  name: heplify-server
data:
  ## https://github.com/sipcapture/homer/wiki/HEPLIFY-SERVER-Settings
  heplify-server.toml: |
    HEPAddr               = "0.0.0.0:9060"
    HEPTCPAddr            = ""
    HEPTLSAddr            = "0.0.0.0:9060"
    HEPWSAddr             = "0.0.0.0:3000"
    ESAddr                = ""
    ESDiscovery           = true
    LokiURL               = ""
    LokiBulk              = 200
    LokiTimer             = 4
    LokiBuffer            = 100000
    LokiHEPFilter         = [1,5,100]
    ForceHEPPayload	      = []
    PromAddr              = "0.0.0.0:9096"
    PromTargetIP          = ""
    PromTargetName        = ""
    DBShema               = "homer7"
    DBDriver              = "postgres"
    DBAddr                = {{ printf "%s:%d" .Values.additionalDbParameters.postgresql.host (.Values.additionalDbParameters.postgresql.port | int) | quote }}
    DBDataTable           = "homer_data"
    DBConfTable           = "homer_config"
    DBUser                = {{ .Values.postgresql.auth.postgresUsername | quote }}
    DBPass                = {{ .Values.postgresql.auth.postgresPassword | quote }}
    DBBulk                = 200
    DBTimer               = 4
    DBBuffer              = 400000
    # Set DBWorker equal to the number of CPUs in the system
    DBWorker              = 8
    DBRotate              = true
    DBPartLog             = "2h"
    DBPartSip             = "1h"
    DBPartQos             = "6h"
    DBDropDays            = {{ .Values.heplifyServer.dbDropDays }}
    DBDropDaysCall        = {{ .Values.heplifyServer.dbDropDaysCall }}
    DBDropDaysRegister    = {{ .Values.heplifyServer.dbDropDaysRegister }}
    DBDropDaysDefault     = {{ .Values.heplifyServer.dbDropDaysDefault }}
    DBDropOnStart         = false
    DBUsageProtection     = true
    DBUsageScheme         = "percentage"
    DBPercentageUsage     = "80%"
    DBMaxSize             = "30MB"
    Dedup                 = false
    DiscardMethod         = []
    AlegIDs               = ["X-CID"]
    CustomHeader          = ["X-Application-Sid", "X-Originating-Carrier", "X-MS-Teams-Tenant-FQDN", "X-Authenticated-User"]
    SIPHeader             = []
    LogDbg                = "hep,sql"
    LogLvl                = "warning"
    LogStd                = true
    LogSys                = false
    Config                = "./heplify-server.toml"
    ConfigHTTPAddr        = ""

    # Examples:
    # -------------------------------------
    # ESAddr          = "http://127.0.0.1:9200"
    # DBShema         = "homer7"
    # DBDriver        = "postgres"
    # LokiURL         = "http://localhost:3100/api/prom/push"
    # LokiHEPFilter   = [1,5,100]
    # PromAddr        = "0.0.0.0:8899"
    # PromTargetIP    = "10.1.2.111,10.1.2.4,10.1.2.5,10.1.2.6,10.12.44.222"
    # PromTargetName  = "sbc_access,sbc_core,kamailio,asterisk,pstn_gateway"
    # AlegIDs         = ["X-CID","P-Charging-Vector,icid-value=\"?(.*?)(?:\"|;|$)","X-BroadWorks-Correlation-Info"]
    # DiscardMethod   = ["OPTIONS","NOTIFY"]
    # CustomHeader    = ["X-CustomerIP","X-Billing"]
    # SIPHeader       = ["callid","callid_aleg","method","ruri_user","ruri_domain","from_user","from_domain","from_tag","to_user","to_domain","to_tag","via","contact_user"]
    # LogDbg          = "hep,sql,loki"
    # LogLvl          = "warning"
    # ConfigHTTPAddr  = "0.0.0.0:9876"
    # -------------------------------------
    # To hot reload PromTargetIP and PromTargetName run:
    # killall -HUP heplify-server