apiVersion: v1
kind: Service
metadata:
  name: heplify-server
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: heplify-server
spec:
  selector:
    app: heplify-server
  ports:
    - name: heplify-server
      port: {{ .Values.heplifyServer.ports.udp }}
      targetPort: {{ .Values.heplifyServer.ports.udp }}
      protocol: UDP
    - name: stats-scraper
      port: {{ .Values.heplifyServer.ports.tcp }}
      targetPort: {{ .Values.heplifyServer.ports.tcp }}
      protocol: TCP
