{{- if and (.Values.vgAudioManager.enabled) (.Values.podMonitors.enabled) }}
{{- with .Values.podMonitors }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prom-cognigy-monitor-cognigy-vg-audio-manager
  namespace: {{ .namespace }}
  labels:
    owner-team: echo
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: vg-audio-manager
{{- end }}
{{- end }}
