{{- if .Values.vgAudioManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vgAudioManager.serviceName | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: vg-audio-manager
    owner-team: echo
spec:
  type: {{ .Values.vgAudioManager.service.type | default "ClusterIP" }}
  selector:
    app: vg-audio-manager
  ports:
    - name: http
      port: {{ .Values.vgAudioManager.service.port | default .Values.vgAudioManager.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
