{{- if and (.Values.ingress.enabled) (.Values.traefik.enabled) (.Values.ingress.jaeger.basicAuthMiddleware.enabled) (not .Values.jaeger.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jaeger-auth
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.jaeger.username | b64enc | quote }}
  password: {{ .Values.jaeger.password | b64enc | quote }}
{{- end }}