{{- if not (.Values.tracing.callTracingEnabled) }}
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: jaeger
    owner-team: echo
spec:
  clusterIP: None
  selector:
    app: jaeger
  ports:
    - name: collector
      port: {{ .Values.jaeger.ports.udp.collector }}
      targetPort: {{ .Values.jaeger.ports.udp.collector }}
      protocol: UDP
    - name: ui
      port: {{ .Values.jaeger.ports.tcp }}
      targetPort: {{ .Values.jaeger.ports.tcp }}
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
{{- end }}