{{- if and (.Values.ingress.enabled) (.Values.traefik.enabled) (.Values.ingress.homer.ipWhiteListMiddleware.enabled) }}
{{- with .Values.ingress.homer.ipWhiteListMiddleware }}
---
# Whitelisting Based on `X-Forwarded-For` with `depth=0`
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelisthomer
  namespace: {{ $.Release.Namespace | quote }}
spec:
  ipWhiteList: {{- toYaml .ipWhiteList | nindent 4 }}
{{- end }}
{{- end }}