{{- if and (.Values.ingress.enabled) (.Values.ingress.jaeger.enabled) (.Values.ingress.jaeger.ipWhiteListMiddleware.enabled) }}
{{- with .Values.ingress.jaeger.ipWhiteListMiddleware }}
---
# Whitelisting Based on `X-Forwarded-For` with `depth=0`
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelistjaeger
  namespace: {{ $.Release.Namespace | quote }}
spec:
  ipAllowList: {{- toYaml .ipWhiteList | nindent 4 }}
{{- end }}
{{- end }}