{{- if and (.Values.ingress.enabled) (.Values.traefik.enabled) (.Values.ingress.vgConnector.ipWhiteListMiddleware.enabled) }}
{{- with .Values.ingress.vgConnector.ipWhiteListMiddleware }}
---
# Whitelisting Based on `X-Forwarded-For` with `depth=0`
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelistvgconnector
  namespace: {{ $.Release.Namespace | quote }}
spec:
  ipAllowList: {{- toYaml .ipWhiteList | nindent 4 }}
{{- end }}
{{- end }}