{{- if and (.Values.postgresql.enabled) (eq .Values.cloud "gcp") -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.gcp.postgresql.storageClassName | quote }}
provisioner: {{ .Values.gcp.postgresql.provisionerName | quote }}
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: {{ .Values.gcp.postgresql.pdType | default "pd-balanced" | quote }}
{{- end -}}