{{- if (.Values.podMonitors.enabled) }}
{{- with .Values.podMonitors }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prom-cognigy-monitor-cognigy-vg-feature-server-all
  namespace: {{ .namespace }}
  labels:
    owner-team: echo
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
    - path: /metrics
      port: fs-drachtio
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - feature-server
          - feature-server-nightly
          - feature-server-legacy
{{- end }}
{{- end }}