apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbc-outbound
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: sbc-outbound
spec:
  selector:
    matchLabels:
      app: sbc-outbound
  {{- if not (and ($.Values.hpa.enabled) ($.Values.hpa.removeReplicas)) }}
  replicas: {{ .Values.sbcOutbound.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: sbc-outbound
      annotations:
        checksum/cognigy-env: {{ include (print $.Template.BasePath "/configurations/cognigy-env.yaml") $ | sha256sum }}
    spec:
      {{- include "image.pullSecrets" $ | nindent 6 }}
      {{- if .Values.sbcOutbound.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.sbcOutbound.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.sbcOutbound.affinity }}
      affinity: {{- include "vg.common.tplvalues.render" (dict "value" .Values.sbcOutbound.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if or (.Values.sbcOutbound.nodeSelector) (and ($.Values.hpa.enabled) ($.Values.hpa.useHpaNodeSelector))}}
      nodeSelector:
        {{- if .Values.sbcOutbound.nodeSelector }}
          {{- include "vg.common.tplvalues.render" (dict "value" .Values.sbcOutbound.nodeSelector "context" $) | nindent 8 }}
        {{- end }}
        {{- if and ($.Values.hpa.enabled) ($.Values.hpa.useHpaNodeSelector) }}
          {{- include "vg.common.tplvalues.render" (dict "value" $.Values.hpa.hpaNodeSelector "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.sbcOutbound.priorityClassName }}
      priorityClassName: {{ .Values.sbcOutbound.priorityClassName }}
      {{- end }}
      {{- if .Values.sbcOutbound.podSecurityContext }}
      securityContext: {{- include "vg.common.tplvalues.render" (dict "value" .Values.sbcOutbound.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if or (.Values.sbcOutbound.tolerations) (and ($.Values.hpa.enabled) ($.Values.hpa.useHpaTolerations))}}
      tolerations: 
        {{- if or (.Values.sbcOutbound.tolerations) }}
          {{- include "vg.common.tplvalues.render" (dict "value" .Values.sbcOutbound.tolerations "context" $) | nindent 8 }}
        {{- end }}
        {{- if and ($.Values.hpa.enabled) ($.Values.hpa.useHpaTolerations) }}
          {{- include "vg.common.tplvalues.render" (dict "value" $.Values.hpa.hpaTolerations "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: sbc-outbound
          image: {{ include "vg.common.image.render" (dict "global" $.Values.global "image" .Values.sbcOutbound.image) }}
          imagePullPolicy: {{ .Values.sbcOutbound.imagePullPolicy }}
          resources: {{- toYaml .Values.sbcOutbound.resources | nindent 12 }}
          ports:
            - name: dtmf
              containerPort: {{ .Values.sbcOutbound.ports.dtmf}}
              protocol: UDP            
            - name: drachtio
              containerPort: {{ .Values.sbcOutbound.ports.tcp }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.health.port }}
              protocol: TCP          
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: {{ .Values.health.port }}
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 10 
          startupProbe:
            httpGet:
              path: /health/startup
              port: {{ .Values.health.port }}
          env:
            - name: NODE_ENV
              value: {{ .Values.global.nodeEnv | quote }}
            - name: K8S 
              value: {{ .Values.global.k8s | quote }}
            - name: K8S_RTPENGINE_SERVICE_NAME
              {{- if .Values.sbc.rtp.useStatefulSet }}
              value: {{ printf "%s:%.0f" .Values.sbc.rtp.headlessServiceName .Values.sbc.rtp.port }}
              {{- else }}
              value: {{ printf "%s:%.0f" .Values.sbc.rtp.serviceName .Values.sbc.rtp.port }}
              {{- end }}
            - name: DRACHTIO_PORT
              value: {{ .Values.sbcOutbound.ports.tcp | quote }}
            - name: DTMF_LISTEN_PORT
              value: {{ .Values.sbcOutbound.ports.dtmf | quote }}
            - name: JAMBONES_LOGLEVEL
              value: {{ .Values.sbcOutbound.logLevel }}
            - name: JAMBONES_TRACK_ACCOUNT_CALLS
              value: {{ .Values.global.track.accountCalls | quote }}
            - name: JAMBONES_TRACK_APP_CALLS
              value: {{ .Values.global.track.applicationCalls | quote }}
            - name: JAMBONES_TRACK_SP_CALLS
              value: {{ .Values.global.track.serviceProviderCalls | quote }}
            - name: ENABLE_METRICS
              value: {{ if .Values.stats.enabled }}{{ print 1 | quote }}{{ else }}{{ print 0 | quote }}{{ end }}
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STATS_TAGS
              value: "pod:$(K8S_POD_NAME)"
            - name: STATS_PROTOCOL
              value: {{ .Values.stats.protocol }}
            - name: STATS_TELEGRAF
              value: {{ if .Values.stats.telegraf }}{{ print 1 | quote }}{{ else }}{{ print 0 | quote }}{{ end }}
            - name: STATS_HOST
              value: {{ .Values.telegraf.serviceName }}
            - name: STATS_PORT
              value: {{ .Values.telegraf.port | quote }}
            - name: STATS_SAMPLE_RATE
              value:  {{ .Values.stats.sampleRate | quote }}
            - name: DRACHTIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: voicegateway-drachtio-secret
                  key: secret
            - name: JAMBONES_MYSQL_HOST
              value: {{ .Values.mysql.host }}
            - name: JAMBONES_MYSQL_DATABASE
              value: {{ .Values.mysql.database.name | quote }}
            - name: JAMBONES_MYSQL_USER
              value: {{ .Values.mysql.auth.username | quote }}
            - name: JAMBONES_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voicegateway-mysql-password
                  key: mysql-password
            - name: JAMBONES_REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: JAMBONES_REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: JAMBONES_TIME_SERIES_HOST
              value: {{ .Values.influxdb.host }}
            - name: TRACING_ENABLED
              value: {{ .Values.tracing.enabled | quote }}
            - name: TRACING_BASE_URL_WITH_PROTOCOL
              value: {{ .Values.tracing.baseUrl | quote }}
            - name: TRACING_ERRORS_ENABLED
              value: {{ .Values.tracing.errorsEnabled | quote }}
            - name: TRACING_SAMPLE_RATE
              value: {{ .Values.tracing.sampleRate | quote }}
            - name: TRACING_EVENTS_SAMPLE_RATE
              value: {{ .Values.tracing.eventsSampleRate | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.tracing.environment | quote }}
            - name: COGNIGY_AI_VERSION
              value: {{ .Chart.Version | trunc 6 | quote }}
            - name: PAD_CRYPTO
              value: {{ .Values.sbcOutbound.padCrypto | quote }}
            - name: JAMBONES_USE_BEST_EFFORT_TLS
              value: {{ if .Values.sbcOutbound.supportBestEffortTls }}{{ print 1 | quote }}{{ else }}{{ print 0 | quote }}{{ end }}
            - name: PRIVATE_VOIP_NETWORK_CIDR
              value: {{ .Values.global.privateVoipNetworkCidr | quote }}
            - name: FEAT_COMPATIBILITY_RFC3261
              value: {{ .Values.sbcOutbound.registerRfc3261 | quote }}
            {{- if .Values.sbcOutbound.extraEnvVars }}
            {{- include "vg.common.tplvalues.render" (dict "value" .Values.sbcOutbound.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: cognigy-env
