apiVersion: v1
kind: Service
metadata:
  name: sbc-outbound
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: sbc-outbound
spec:
  selector:
    app: sbc-outbound
  ports:
    - name: sbc-outbound
      port: {{ .Values.sbcOutbound.ports.tcp }}
      targetPort: {{ .Values.sbcOutbound.ports.tcp }}
      protocol: TCP
  