apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: {{ $.Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: {{ .Values.webapp.replicaCount }}
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        checksum/cognigy-env: {{ include (print $.Template.BasePath "/configurations/cognigy-env.yaml") $ | sha256sum }}
    spec:
      {{- include "image.pullSecrets" $ | nindent 6 }}
      {{- if .Values.webapp.affinity }}
      affinity: {{- include "vg.common.tplvalues.render" (dict "value" .Values.webapp.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.webapp.nodeSelector }}
      nodeSelector: {{- include "vg.common.tplvalues.render" (dict "value" .Values.webapp.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.webapp.priorityClassName }}
      priorityClassName: {{ .Values.webapp.priorityClassName }}
      {{- end }}
      {{- if .Values.webapp.podSecurityContext }}
      securityContext: {{- include "vg.common.tplvalues.render" (dict "value" .Values.webapp.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.webapp.tolerations }}
      tolerations: {{- include "vg.common.tplvalues.render" (dict "value" .Values.webapp.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: webapp
          image: {{ include "vg.common.image.render" (dict "global" $.Values.global "image" .Values.webapp.image) }}
          imagePullPolicy: {{ .Values.webapp.imagePullPolicy }}
          resources: {{- toYaml .Values.webapp.resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.global.nodeEnv | quote }}
            - name: API_BASE_URL
              value: {{ .Values.api.protocol }}://{{ .Values.ingress.api.host }}/v1
            - name: TRACING_ENABLED
              value: {{ .Values.tracing.enabled | quote }}
            - name: TRACING_BASE_URL_WITH_PROTOCOL
              value: {{ .Values.tracing.baseUrl | quote }}      
            - name: TRACING_ERRORS_ENABLED
              value: {{ .Values.tracing.errorsEnabled | quote }}
            - name: TRACING_SAMPLE_RATE
              value: {{ .Values.tracing.sampleRate | quote }}
            - name: TRACING_EVENTS_SAMPLE_RATE
              value: {{ .Values.tracing.eventsSampleRate | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.tracing.environment | quote }}
            - name: COGNIGY_AI_VERSION
              value: {{ regexFind "^[0-9]+\\.[0-9]+\\.[0-9]+" .Chart.Version | quote }}
            - name: COGNIGY_VG_VERSION
              value: {{ regexFind "^[0-9]+\\.[0-9]+\\.[0-9]+" .Chart.Version | quote }}
            - name: COGNIGY_URL
              value: {{ .Values.webapp.cognigyUrl | quote }}
            - name: ENABLE_COGNIGY_LOGIN
              value: {{ .Values.webapp.enableCognigyLogin | quote }}
            - name: DISABLE_SIP_CLIENT
              value: {{ .Values.webapp.disableSipClient | quote }}
            - name: DISABLE_SP_LIMITS
              value: {{ .Values.webapp.disableSpLimits | quote }}
            - name: ENABLE_MSTEAMS_ROUTING
              value: {{ .Values.webapp.enableMsTeamsRouting | quote }}
            - name: DISABLE_CUSTOM_SPEECH
              value: {{ .Values.webapp.disableCustomSpeech | quote }}
            - name: ENABLE_ALL_SPEECH_PROVIDERS
              value: {{ .Values.webapp.enableAllSpeechProviders | quote }}
            - name: ENABLE_ENABLE_SMS
              value: {{ .Values.webapp.enableSms | quote }}
            - name: DISABLE_DEFAULT_TRUNK_ROUTING
              value: {{ .Values.webapp.disableDefaultTrunkRouting | quote }}
            - name: DISABLE_LCR
              value: {{ .Values.webapp.disableLcr | quote }}
            - name: DISABLE_TRACING
              value: {{ .Values.webapp.disableTracing | quote }}
            - name: ENABLE_FORGOT_PASSWORD
              value: {{ .Values.webapp.enableForgotPassword | quote }}
            - name: DISABLE_CALL_RECORDING
              value: {{ .Values.webapp.disableCallRecording | quote }}
            - name: VG_SENTRY_TRACING_ENABLED
              value: {{ .Values.tracing.callTracingEnabled | quote }}
            - name: ENABLE_TTS_ELEVENLABS
              value: {{ .Values.webapp.enableTtsElevenlabs | quote }}
            - name: ENABLE_TTS_ELEVENLABS_OPTIONS
              value: {{ .Values.webapp.enableTtsElevenlabsOptions | quote }}            
            - name: ENABLE_DEEPGRAM
              value: {{ .Values.webapp.enableDeepgram | quote }}            
            - name: ENABLE_ON_PREMISES_DEEPGRAM
              value: {{ .Values.webapp.enableOnPremisesDeepgram | quote }}
            - name: ENABLE_ON_PREMISES_NUANCE
              value: {{ .Values.webapp.enableOnPremisesNuance | quote }}
            - name: ENABLE_ON_PREM_AZURE_SPEECH
              value: {{ .Values.webapp.enableOnPremisesAzureSpeech | quote }}
            - name: ENABLE_PING_OPTIONS
              value: {{ .Values.webapp.enablePingOptions | quote }}
            {{- if .Values.webapp.extraEnvVars }}
            {{- include "vg.common.tplvalues.render" (dict "value" .Values.webapp.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: cognigy-env
