apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: {{ $.Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: {{ .Values.webapp.replicaCount }}
  template:
    metadata:
      labels:
        app: webapp
    spec:
    {{- include "image.pullSecrets" $ | nindent 6 }}
      containers:
        - name: webapp
          image: {{ .Values.webapp.image }}
          imagePullPolicy: {{ .Values.webapp.imagePullPolicy }}
          resources: {{- toYaml .Values.webapp.resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.global.nodeEnv | quote }}
            - name: API_BASE_URL
              value: {{ .Values.api.protocol }}://{{ .Values.ingress.api.host }}/v1
            - name: VITE_APP_ENABLE_ACCOUNT_LIMITS_ALL
              value: {{ .Values.webapp.enableAccountLimits | quote }}
            - name: VITE_APP_ENABLE_ALL_SPEECH_PROVIDERS
              value: {{ .Values.webapp.enableAllSpeechProviders | quote }}
            - name: TRACING_ENABLED
              value: {{ .Values.tracing.enabled | quote }}
            - name: TRACING_BASE_URL_WITH_PROTOCOL
              value: {{ .Values.tracing.baseUrl | quote }}      
            - name: TRACING_ERRORS_ENABLED
              value: {{ .Values.tracing.errorsEnabled | quote }}
            - name: TRACING_EVENTS_SAMPLE_RATE
              value: {{ .Values.tracing.eventsSampleRate | quote }}
            - name: COGNIGY_AI_VERSION
              value: {{ .Values.global.cognigyVgVersion | quote }}
