apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  ports:
    - name: webapp
      port: {{ .Values.webapp.port }}
      targetPort: {{ .Values.webapp.port }}
      protocol: TCP
